apiVersion: v1
kind: Service
metadata:
  name: go-grpcsrv-gptclient
spec:
   type: ClusterIP
   selector:
    app: go-grpcsrv-gptclient
   ports:
   - name: http2-gptclient
     protocol: TCP
     port: 8081
   clusterIP: None