apiVersion: skaffold/v2beta26
kind: Config
metadata:
    name: go-grpcsrv-gptclient
build:
    artifacts:
      - image: go-grpcsrv-gptclient
        ko:
          fromImage: gcr.io/distroless/static:nonroot
    tagPolicy:
      inputDigest: {}
deploy:
  kubectl:
      manifests:
      - k8s/*.yaml
