apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: go-grpc-srv-gptclient
build:
  artifact:
    - image: go-grpc-srv-gptclient
      ko:
        fromImage: gcr.io/distroless/static:nonroot
  tagPolicy:
    inputDigest: {}
  deploy:
    kubectl:
      manifests:
        -k8s/*.yaml