// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: gpt.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GeneratePersonaEditServiceClient is the client API for GeneratePersonaEditService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GeneratePersonaEditServiceClient interface {
	GeneratePersonaEdit(ctx context.Context, in *InputAndInstruction, opts ...grpc.CallOption) (*PersonaResponse, error)
}

type generatePersonaEditServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGeneratePersonaEditServiceClient(cc grpc.ClientConnInterface) GeneratePersonaEditServiceClient {
	return &generatePersonaEditServiceClient{cc}
}

func (c *generatePersonaEditServiceClient) GeneratePersonaEdit(ctx context.Context, in *InputAndInstruction, opts ...grpc.CallOption) (*PersonaResponse, error) {
	out := new(PersonaResponse)
	err := c.cc.Invoke(ctx, "/myapp.GeneratePersonaEditService/GeneratePersonaEdit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeneratePersonaEditServiceServer is the server API for GeneratePersonaEditService service.
// All implementations must embed UnimplementedGeneratePersonaEditServiceServer
// for forward compatibility
type GeneratePersonaEditServiceServer interface {
	GeneratePersonaEdit(context.Context, *InputAndInstruction) (*PersonaResponse, error)
	mustEmbedUnimplementedGeneratePersonaEditServiceServer()
}

// UnimplementedGeneratePersonaEditServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGeneratePersonaEditServiceServer struct {
}

func (UnimplementedGeneratePersonaEditServiceServer) GeneratePersonaEdit(context.Context, *InputAndInstruction) (*PersonaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GeneratePersonaEdit not implemented")
}
func (UnimplementedGeneratePersonaEditServiceServer) mustEmbedUnimplementedGeneratePersonaEditServiceServer() {
}

// UnsafeGeneratePersonaEditServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeneratePersonaEditServiceServer will
// result in compilation errors.
type UnsafeGeneratePersonaEditServiceServer interface {
	mustEmbedUnimplementedGeneratePersonaEditServiceServer()
}

func RegisterGeneratePersonaEditServiceServer(s grpc.ServiceRegistrar, srv GeneratePersonaEditServiceServer) {
	s.RegisterService(&GeneratePersonaEditService_ServiceDesc, srv)
}

func _GeneratePersonaEditService_GeneratePersonaEdit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputAndInstruction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeneratePersonaEditServiceServer).GeneratePersonaEdit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/myapp.GeneratePersonaEditService/GeneratePersonaEdit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeneratePersonaEditServiceServer).GeneratePersonaEdit(ctx, req.(*InputAndInstruction))
	}
	return interceptor(ctx, in, info, handler)
}

// GeneratePersonaEditService_ServiceDesc is the grpc.ServiceDesc for GeneratePersonaEditService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GeneratePersonaEditService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "myapp.GeneratePersonaEditService",
	HandlerType: (*GeneratePersonaEditServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GeneratePersonaEdit",
			Handler:    _GeneratePersonaEditService_GeneratePersonaEdit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gpt.proto",
}

// GeneratePersonaCompletionServiceClient is the client API for GeneratePersonaCompletionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GeneratePersonaCompletionServiceClient interface {
	GeneratePersonaCompletion(ctx context.Context, in *Prompt, opts ...grpc.CallOption) (*PersonaResponse, error)
}

type generatePersonaCompletionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGeneratePersonaCompletionServiceClient(cc grpc.ClientConnInterface) GeneratePersonaCompletionServiceClient {
	return &generatePersonaCompletionServiceClient{cc}
}

func (c *generatePersonaCompletionServiceClient) GeneratePersonaCompletion(ctx context.Context, in *Prompt, opts ...grpc.CallOption) (*PersonaResponse, error) {
	out := new(PersonaResponse)
	err := c.cc.Invoke(ctx, "/myapp.GeneratePersonaCompletionService/GeneratePersonaCompletion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeneratePersonaCompletionServiceServer is the server API for GeneratePersonaCompletionService service.
// All implementations must embed UnimplementedGeneratePersonaCompletionServiceServer
// for forward compatibility
type GeneratePersonaCompletionServiceServer interface {
	GeneratePersonaCompletion(context.Context, *Prompt) (*PersonaResponse, error)
	mustEmbedUnimplementedGeneratePersonaCompletionServiceServer()
}

// UnimplementedGeneratePersonaCompletionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGeneratePersonaCompletionServiceServer struct {
}

func (UnimplementedGeneratePersonaCompletionServiceServer) GeneratePersonaCompletion(context.Context, *Prompt) (*PersonaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GeneratePersonaCompletion not implemented")
}
func (UnimplementedGeneratePersonaCompletionServiceServer) mustEmbedUnimplementedGeneratePersonaCompletionServiceServer() {
}

// UnsafeGeneratePersonaCompletionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeneratePersonaCompletionServiceServer will
// result in compilation errors.
type UnsafeGeneratePersonaCompletionServiceServer interface {
	mustEmbedUnimplementedGeneratePersonaCompletionServiceServer()
}

func RegisterGeneratePersonaCompletionServiceServer(s grpc.ServiceRegistrar, srv GeneratePersonaCompletionServiceServer) {
	s.RegisterService(&GeneratePersonaCompletionService_ServiceDesc, srv)
}

func _GeneratePersonaCompletionService_GeneratePersonaCompletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Prompt)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeneratePersonaCompletionServiceServer).GeneratePersonaCompletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/myapp.GeneratePersonaCompletionService/GeneratePersonaCompletion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeneratePersonaCompletionServiceServer).GeneratePersonaCompletion(ctx, req.(*Prompt))
	}
	return interceptor(ctx, in, info, handler)
}

// GeneratePersonaCompletionService_ServiceDesc is the grpc.ServiceDesc for GeneratePersonaCompletionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GeneratePersonaCompletionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "myapp.GeneratePersonaCompletionService",
	HandlerType: (*GeneratePersonaCompletionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GeneratePersonaCompletion",
			Handler:    _GeneratePersonaCompletionService_GeneratePersonaCompletion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gpt.proto",
}
